# coding: utf-8

"""
    Aerpaw Gateway

    This is Aerpaw gateway service to interact with Emulab  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ericafu@renci.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import aerpawgw_client
from aerpawgw_client.models.userkey import Userkey  # noqa: E501
from aerpawgw_client.rest import ApiException


class TestUserkey(unittest.TestCase):
    """Userkey unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserkey(self):
        """Test Userkey"""
        # FIXME: construct object with mandatory attributes with example values
        # model = aerpawgw_client.models.userkey.Userkey()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
