# coding: utf-8

"""
    Aerpaw Gateway

    This is Aerpaw gateway service to interact with Emulab  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ericafu@renci.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import aerpawgw_client
from aerpawgw_client.api.user_api import UserApi  # noqa: E501
from aerpawgw_client.rest import ApiException


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self):
        self.api = UserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_user(self):
        """Test case for create_user

        create user on emulab testbed  # noqa: E501
        """
        pass

    def test_delete_user(self):
        """Test case for delete_user

        delete user  # noqa: E501
        """
        pass

    def test_get_user(self):
        """Test case for get_user

        get user information  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
