# coding: utf-8

"""
    Aerpaw Gateway

    This is Aerpaw gateway service to interact with Emulab  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ericafu@renci.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import aerpawgw_client
from aerpawgw_client.api.reservation_api import ReservationApi  # noqa: E501
from aerpawgw_client.rest import ApiException


class TestReservationApi(unittest.TestCase):
    """ReservationApi unit test stubs"""

    def setUp(self):
        self.api = ReservationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_reservation(self):
        """Test case for create_reservation

        create reservation  # noqa: E501
        """
        pass

    def test_delete_reservation(self):
        """Test case for delete_reservation

        delete reservation  # noqa: E501
        """
        pass

    def test_get_reservation(self):
        """Test case for get_reservation

        get reservation under user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
