# coding: utf-8

"""
    Aerpaw Gateway

    This is Aerpaw gateway service to interact with Emulab  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ericafu@renci.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Node(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'component_name': 'str',
        'component_id': 'str',
        'type': 'str',
        'available': 'bool'
    }

    attribute_map = {
        'component_name': 'component_name',
        'component_id': 'component_id',
        'type': 'type',
        'available': 'available'
    }

    def __init__(self, component_name=None, component_id=None, type=None, available=None):  # noqa: E501
        """Node - a model defined in Swagger"""  # noqa: E501
        self._component_name = None
        self._component_id = None
        self._type = None
        self._available = None
        self.discriminator = None
        if component_name is not None:
            self.component_name = component_name
        if component_id is not None:
            self.component_id = component_id
        if type is not None:
            self.type = type
        if available is not None:
            self.available = available

    @property
    def component_name(self):
        """Gets the component_name of this Node.  # noqa: E501


        :return: The component_name of this Node.  # noqa: E501
        :rtype: str
        """
        return self._component_name

    @component_name.setter
    def component_name(self, component_name):
        """Sets the component_name of this Node.


        :param component_name: The component_name of this Node.  # noqa: E501
        :type: str
        """

        self._component_name = component_name

    @property
    def component_id(self):
        """Gets the component_id of this Node.  # noqa: E501


        :return: The component_id of this Node.  # noqa: E501
        :rtype: str
        """
        return self._component_id

    @component_id.setter
    def component_id(self, component_id):
        """Sets the component_id of this Node.


        :param component_id: The component_id of this Node.  # noqa: E501
        :type: str
        """

        self._component_id = component_id

    @property
    def type(self):
        """Gets the type of this Node.  # noqa: E501


        :return: The type of this Node.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Node.


        :param type: The type of this Node.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def available(self):
        """Gets the available of this Node.  # noqa: E501


        :return: The available of this Node.  # noqa: E501
        :rtype: bool
        """
        return self._available

    @available.setter
    def available(self, available):
        """Sets the available of this Node.


        :param available: The available of this Node.  # noqa: E501
        :type: bool
        """

        self._available = available

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Node, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Node):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
