# coding: utf-8

"""
    Aerpaw Gateway

    This is Aerpaw gateway service to interact with Emulab  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ericafu@renci.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Resource(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'nodes': 'list[Node]',
        'vnodes': 'list[Vnode]',
        'rspec': 'str'
    }

    attribute_map = {
        'nodes': 'nodes',
        'vnodes': 'vnodes',
        'rspec': 'rspec'
    }

    def __init__(self, nodes=None, vnodes=None, rspec=None):  # noqa: E501
        """Resource - a model defined in Swagger"""  # noqa: E501
        self._nodes = None
        self._vnodes = None
        self._rspec = None
        self.discriminator = None
        if nodes is not None:
            self.nodes = nodes
        if vnodes is not None:
            self.vnodes = vnodes
        if rspec is not None:
            self.rspec = rspec

    @property
    def nodes(self):
        """Gets the nodes of this Resource.  # noqa: E501


        :return: The nodes of this Resource.  # noqa: E501
        :rtype: list[Node]
        """
        return self._nodes

    @nodes.setter
    def nodes(self, nodes):
        """Sets the nodes of this Resource.


        :param nodes: The nodes of this Resource.  # noqa: E501
        :type: list[Node]
        """

        self._nodes = nodes

    @property
    def vnodes(self):
        """Gets the vnodes of this Resource.  # noqa: E501


        :return: The vnodes of this Resource.  # noqa: E501
        :rtype: list[Vnode]
        """
        return self._vnodes

    @vnodes.setter
    def vnodes(self, vnodes):
        """Sets the vnodes of this Resource.


        :param vnodes: The vnodes of this Resource.  # noqa: E501
        :type: list[Vnode]
        """

        self._vnodes = vnodes

    @property
    def rspec(self):
        """Gets the rspec of this Resource.  # noqa: E501


        :return: The rspec of this Resource.  # noqa: E501
        :rtype: str
        """
        return self._rspec

    @rspec.setter
    def rspec(self, rspec):
        """Sets the rspec of this Resource.


        :param rspec: The rspec of this Resource.  # noqa: E501
        :type: str
        """

        self._rspec = rspec

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Resource, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Resource):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
